import type { Metadata } from "next";

import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';

import "./../../public/css/Home.css";
import "./../../public/css/carrinho.css";
import "./../../public/css/categoria.css";
import "./../../public/css/Banner.css";





import "./../../public/css/dashprodutos/produto.css";
import "./../../public/css/dashprodutos/Modal.css";
import "./../../public/css/produtos/produto.css";
import "./../../public/css/produtos/produtocard.css";
import "./../../public/css/produtos/carrinho.css";
import "./../../public/css/produtos/modal.css";
import "./../../public/css/produtos/CategoriaClient.css";
import "./../../public/css/produtos/cupon.css";
import "./../../public/css/produtos/card.css";
import "./../../public/css/produtos/pedido.css";



import "./../../public/css/dash.css";

import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Imperio Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={` antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
